##Numpy :
NumPy, which stands for Numerical Python, is the fundamental open-source library used for scientific computing, data analysis, and machine learning in Python.


##Numpy Library Installation:

In [11]:
!pip install numpy


In [12]:
import numpy as np

## create array using numpy
##create a 1D array
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))  #for the datatype
print(arr1.shape)  #shape of the array
print(arr1.ndim)   #for looking up the dimensions of the array


[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
1


In [13]:
np.arange(0,10,2).reshape(5)      #Suppose you have the array But while reshaping it - you give the wrong value

array([0, 2, 4, 6, 8])

In [14]:
## 2d array
arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])   #2 rows and 5 columns
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [15]:
#np.arange([start,] stop, [step,] dtype=None)    --Syntax   The stop here is Exclusive and the Start in Inclusive
np.arange(0,10,2).reshape(5,1)


array([[0],
       [2],
       [4],
       [6],
       [8]])

In [16]:
np.ones((3,4))    #Matrix Cotaining all the value as 1's

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
#CONVERT all the values from the array from float to Integer
float_matrix = np.array([[1.2, 2.7, 3.9],
                         [4.1, 5.5, 6.8]])

# Convert to integer
int_matrix = float_matrix.astype(int)  #We use .astype(datatype) as the syntax

print(int_matrix)

[[1 2 3]
 [4 5 6]]


In [18]:
#Sometime we need to round off in better proportion
matrix = np.array([1.2, 2.7, 3.9])

# Rounds 2.7 to 3.0, and 3.9 to 4.0, then converts to int
rounded_int = np.round(matrix).astype(int)

print(rounded_int)


[1 3 4]


In [19]:
## identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
## Attributes of Numpy Array
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("Shape:", arr.shape)  #
print("Number of dimensions:", arr.ndim)  # Output: 2
print("Size (number of elements):", arr.size)  # Output: 6
print("Data type:", arr.dtype)  # Output: int32 (may vary based on platform)
print("Item size (in bytes):", arr.itemsize)  # Output: 8 (may vary based on platform)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int64
Item size (in bytes): 8


In [21]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr3 = arr1+arr2
print(arr3,arr3.dtype)



# Element-wise multiplication
print("Multiplication:", arr1 * arr2)

# Element-wise division
print("Division:", arr1 / arr2)

[5 7 9] int64
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]


In [22]:
## Universal Function
arr=np.array([2,3,4,5,6])

## square root
print(np.sqrt(arr))

## Exponential
print(np.exp(arr))

## Sine
print(np.sin(arr))

## natural log

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]


##Slicing and Indexing

In [23]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array : \n", arr)

Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [32]:
print(arr[0:,1:])

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


In [33]:
print(arr[1:,1:3])  #Remember the Inclusive & Exclusive

[[ 6  7]
 [10 11]]


In [43]:
print(arr[0][0],end="\n")
print(arr[0][1],end="\n")
print(arr[2][2],end="\n")

1
2
11


In [42]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# Iterate over every element seamlessly
for x in np.nditer(matrix):   #N - dimensional Iterator
    print(x, end=" ")
# Output: 1 2 3 4 5 6


1 2 3 4 5 6 

In [44]:
## Modify array elements
arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [45]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
matrix[1:]=100
print(matrix)

[[  1   2   3]
 [100 100 100]]


###Statistical Data

In [49]:
data = np.array([1,2,3,4,5,6,7,8,9,10])
mean = np.mean(data)
median = np.median(data)
std_dev = np.std(data)
variance = np.var(data)

print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)
print("Variance:", variance)
#

Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [50]:
normalized_data = (data - mean) / std_dev
print("Normalized data:", normalized_data)

Normalized data: [-1.5666989  -1.21854359 -0.87038828 -0.52223297 -0.17407766  0.17407766
  0.52223297  0.87038828  1.21854359  1.5666989 ]


### Logical Operations


In [51]:
data=np.array([1,2,3,4,5,6,7,8,9,10])
data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])